### ISSUE TITLE
push消息设置有问题？

### ISSUE THREAD

**Issue by justincnn** [QiuYueBaiJXW/CN-Unicom-AutoSign#14]
你好，我key填了推送酱的key，但是推送一直没成功，这里有什么需要注意的么？谢谢

**Comment by QiuYueBaiJXW** [comment]
因为我没写推送酱的代码
当然不会推送了
你是不是看串项目了哈哈

**Comment by justincnn** [comment]
> 因为我没写推送酱的代码
> 当然不会推送了
> 你是不是看串项目了哈哈

嗯嗯，请问可以增加推送代码么？谢谢啊，嘿嘿
