### ISSUE TITLE
很好用

### ISSUE THREAD

**Issue by fhqswcan** [QiuYueBaiJXW/CN-Unicom-AutoSign#6]
使用抓包软件后 无法登陆

**Comment by QiuYueBaiJXW** [comment]
> 使用抓包软件后 无法登陆

报错是啥？没图我怎么知道啥情况

**Comment by fhqswcan** [comment]
安卓 10.0 使用httpcanary 抓包 客户端直接拒绝登录

**Comment by QiuYueBaiJXW** [comment]
> 安卓 10.0 使用httpcanary 抓包 客户端直接拒绝登录 关键我这边无法上传图片

那你换一个软件抓包呗，安卓我不太清楚

**Comment by fhqswcan** [comment]
和软件没有直接关系 最新版本客户端升级了 登录这块和支付宝设计的一样 在网上搜索了下 使用平行世界类型虚拟机 然后直接抓虚拟机里面的包就可以了，感谢作者的回复
